name: custom-create-compute

on:
  workflow_call:
    inputs:
      resource_group:
        description: "Azure Resource Group name"
        required: true
        type: string
      workspace_name:
        description: "Azure ML Workspace name"
        required: true
        type: string
      cluster_name:
        description: "Azure ML compute cluster name"
        required: true
        type: string
      size:
        description: "VM size for the compute cluster (e.g., Standard_DS3_v2)"
        required: true
        type: string
      min_instances:
        description: "Minimum number of nodes"
        required: false
        default: 0
        type: number
      max_instances:
        description: "Maximum number of nodes"
        required: false
        default: 2
        type: number
      cluster_tier:
        description: "Optional tier (Dedicated or LowPriority). If blank, defaults to Dedicated."
        required: false
        default: ""
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true

jobs:
  create-compute:
    runs-on: ubuntu-latest

    steps:
      - name: Pre Az CLI login
        run: |
          az version

      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: install-extension
        run: |
          az extension add -n ml -y

      - name: update-extension
        run: |
          az extension update -n ml

      # If cluster_tier is blank, create with Dedicated
      - name: create-compute-default-tier
        if: ${{ inputs.cluster_tier == '' }}
        run: |
          az ml compute create --name "${{ inputs.cluster_name }}" --type AmlCompute --tier Dedicated --size "${{ inputs.size }}" --min-instances ${{ inputs.min_instances }} --max-instances ${{ inputs.max_instances }} --resource-group "${{ inputs.resource_group }}" --workspace-name "${{ inputs.workspace_name }}"

      # If cluster_tier is provided, use it
      - name: create-compute-using-tier
        if: ${{ inputs.cluster_tier != '' }}
        run: |
          az ml compute create --name "${{ inputs.cluster_name }}" --type AmlCompute --tier "${{ inputs.cluster_tier }}" --size "${{ inputs.size }}" --min-instances ${{ inputs.min_instances }} --max-instances ${{ inputs.max_instances }} --resource-group "${{ inputs.resource_group }}" --workspace-name "${{ inputs.workspace_name }}"

      - name: Post Az CLI login
        run: |
          az account show
